on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: 🧑‍💻 Install dependencies
        run: pnpm install
      - name: 🙊 Install language servers
        run: |
          npm install -g typescript typescript-language-server
          which typescript-language-server
      - name: ⚒️ Build
        run: pnpm build
      - name: 🧪 Run tests
        run: pnpm test
